require:
  - rubocop-rspec

inherit_from:
  - ./rubocop.yml
  - ./rubocop-rspec.yml

Gemspec/RequireMFA:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/rubocop-mdsol.rb

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
