require:
  - rubocop-rspec

inherit_from:
  - ./rubocop.yml
  - ./rubocop-rspec.yml

AllCops:
  TargetRubyVersion: 2.5

Naming/FileName:
  Exclude:
    - lib/rubocop-mdsol.rb

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
