dist: focal
language: ruby
cache: bundler

rvm:
  - 2.7
  - 3.0
  - 3.1

script:
  - bundle exec rubocop
  - bundle exec rspec

before_install:
  - gem update --system --force -N > /dev/null && echo "Rubygems version $(gem --version)" && bundle --version

deploy:
  edge: true # opt in to dpl v2
  provider: rubygems
  on:
    tags: true
  api_key:
    secure: ukovPMRMQAbsbMLEy7ZiPVaXyAazdrCWLfB+RtOjEUZu06blr3C3UsmgDO05OQ1LKgeT3nXuXQ592wdsMUAdysYI+cGc1YACLmTqysYNMm/+m0Uaglb/8XHKBXaVby881r4bUF9o9M+l52pL7PUWURvDCqj1n8kDpzbYFczDzORFkfeNtaXDju+gqxJQ790ohL1dFjXoG1qr73mlH0Gc1I5diYBzY/byTyZFVz5bUBQWCwTs/hM9dFMMREyhpEVLaRbrwZb70ir3j6JDV/3x9/D0IKNlJzOTd0SXRigjljHZFfZpqXF90rQAHnEOn3QdcHWi02XlvSoEwh5nm/BeHmq16bhCMzB7PniOxGRgC+zj2t60gNXajz1XljR9mNl3949ICPYocAmWEZbG/j7pB5QsxyI5x4XAplQ7M1Z05KQNYCTyZT5unGpio9Nrj0GnazSu2iwzmj7/hsaa0DWmqeSzK4IsKK8QWjdBB978auEgeC7g86zNDehHj8viB67tL3n2gox1V5JEkrx0dAlGLOJhIAlcBGaS99d694B5WA+4hZDIXHH0IYYSHpaKBbzBVi1zfncRvHX98B5C1+CYj+ewR4UT+PEc9+OKMNrM84kw+f+mPHs3MRrZQVVX/+QBqCb1L3YFSG9pO56kjgMP/CPdJiPYQukWwbYKe6Hx7MA=
